
 name: CI/CD Pipeline

 on:
   push:
     branches: [ master, main ]
   pull_request:
     branches: [ master, main ]

 # Permissions nécessaires pour GitHub Pages
 permissions:
   contents: read
   pages: write
   id-token: write

 jobs:
   test:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4

       - name: Setup Node.js
         uses: actions/setup-node@v4
         with:
           node-version: '18'
           cache: 'npm'

       - name: Install dependencies
         run: npm ci

       - name: Lint
         run: npm run lint || echo "Lint check skipped"

       - name: Run tests with coverage
         run: npm run coverage

       - name: Check coverage threshold
         run: |
           COVERAGE=$(cat coverage/coverage-summary.json | jq '.total.lines.pct')
           if (( $(echo "$COVERAGE < 60" | bc -l) )); then
             echo "Test coverage is below 60%: $COVERAGE%"
             exit 1
           else
             echo "Test coverage is $COVERAGE%"
           fi

       - name: Upload coverage reports
         uses: actions/upload-artifact@v4
         with:
           name: coverage-report
           path: coverage/

